### ISSUE TITLE
print issues

### ISSUE THREAD

**Issue by tomazzz369z** [SocraticBliss/ps4_unfself#1]
Digest issue or whole Extended Information on some files.
**This is only print issue, decrypted files are fine.**

https://www51.zippyshare.com/v/ZJBwPdqQ/file.html

libSceFios2.prx

now:

Digest: 000000000000000015E8980001C42D7633700FF0BA8ADC361477F8E78EAD5880

should be:

Digest: 15E8980001C42D7633700FF0BA8ADC361477F8E78EAD58807E18166396D0EA30

also Authentication ID is printed as Type

[SELF Extended Information]
Authentication ID: 0x0
Type: 0x35000003ACC21FE1 (Unknown)
Application Version: 0x1
Firmware Version: 0x0
Digest: 000000000000000015E8980001C42D7633700FF0BA8ADC361477F8E78EAD5880

---

on second prx file digest is printed fine

libc.prx

Digest: 3C8419661039F275C4B28290D02B58F26790EFBE85D86926A0BBA4C8BEA636A1

---

the same issue on eboot.bin

[SELF Version]
Version: 246992

Parsing PS4 SELF Extended Information...

[SELF Extended Information]
Authentication ID: 0x0
Type: 0x34000003ACC21FE1 (Unknown)
Application Version: 0x1
Firmware Version: 0x0
Digest: 00000000000000004D41EAFB9388DD6A49B34E5FA7973E091B2E65BCB7E762A7

regards

**Comment by SocraticBliss** [comment]
Sorry it took me so long to write back! Thanks for the fixes! Can you make a pull request?
